<?php
// adm/get_semester.php

header('Content-Type: application/json');

if (isset($_POST['database_name'])) {
    $server = "localhost"; 
    $username = "root";    
    $password = "";    
    $database = $_POST['database_name'];

    // Basic security check to prevent connecting to unauthorized DBs if needed
    // For now assuming the input is valid as it comes from a dropdown generated by the server

    $conn = new mysqli($server, $username, $password, $database);

    if ($conn->connect_error) {
        echo json_encode(['error' => 'Connection failed: ' . $conn->connect_error]);
        exit;
    }

    // Check if tapel table exists and get semesters
    $query = "SELECT DISTINCT smt FROM tapel ORDER BY smt ASC";
    $result = $conn->query($query);

    $semesters = [];
    if ($result) {
        if ($result->num_rows > 0) {
            while ($row = $result->fetch_assoc()) {
                $semesters[] = $row['smt'];
            }
        } else {
             // If no data in tapel, return default empty or maybe 1 & 2?
             // Returning empty list so frontend handles "No semester data" or defaults
        }
    } else {
         // Table might not exist or other error
         // sending error to frontend
         echo json_encode(['error' => 'Query error or table not found']);
         $conn->close();
         exit;
    }

    echo json_encode($semesters);
    $conn->close();
} else {
    echo json_encode(['error' => 'No database name provided']);
}
?>
